# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wHaRQwoIgfDn7mKveuY_irYoqGJLJfOq
"""



"""My name is **Arielle Kann** . Something_interesting_ about me is that i am a single mom to a four year old little girl."""